extraction:
  cpp:
    after_prepare: 
      - python report.py 81
  cobol:
    after_prepare: 
      - python report.py 81
  csharp:
    after_prepare: 
      - python report.py 81
  java:
    after_prepare: 
      - python report.py 81
  javascript:
    after_prepare: 
      - python report.py 81
  python:
    after_prepare: 
      - python report.py 81
